### ISSUE TITLE
Split engine and UI logic

### ISSUE THREAD

**Issue by eduherminio** [Tumpa-Prizrak/ChessPlatform#2]
Hey there!

Before you go any further, here's my recommendation: keep chess stuff and UI stuff separated.
Similar to what I recommended, but too late, to Seb in https://github.com/SebLague/Chess-Challenge/issues/360.

You can have a top level solution (`.sln`) file that points to different project (`.csproj`) files, and those project files can reference each other (as long as you don't create circular references).
In this case, the UI project would want reference the chess one (and if you want to create a tomorrow a purely CLI project, for instance for UCI support, you could add that and make it reference the chess one, same for an API project, etc.). I'm doing something similar in [TeenyLynx/tree/split-ui-from-engine-logic](https://github.com/lynx-chess/TeenyLynx/tree/split-ui-from-engine-logic) with Seb's base repo, in case you want to take a look.

Thanks for the mention in the readme BTW, you really didn't need to. I'll make sure to add some description to yesterday's PR explaining why that solves the issue.

**Comment by eduherminio** [comment]
PS: You told us to please not to contact you, but feel free to reach out yourself if you need any further help/advice/opinions/to chat.

**Comment by Tumpa-Prizrak** [comment]
Thank you for your advise! I'll do it and reference it in my next commit. I think I'll create separate them into different `.csproj`

What about contacting: I always burn all the bridges down after leaving server/community. It's really hard for me to argue about some things that I do, so I have huge list of blacklisted users. You and all others are totally okay to contact me about some other stuff: asking for help with projects, etc. So I'm okay with DMs until you're not spamming "Why you left?"
